In [9]:
import numpy as np

In [10]:
x = np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [11]:
arr = np.array(70)
print(arr)

70


In [12]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [15]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [16]:
arr = np.array([[6,7,8,9,10],[1,2,3,4,5]])
print(arr[-2, -1])

10


In [19]:
arr = np.array([1,2,3,4,5,6,7,8,10])
print(arr[2::3])
print(arr[::3])

[ 3  6 10]
[1 4 7]


In [20]:
arr = np.array([[1,2,3],[3,2,3]])
for x in arr:
    print("array")
    print(x)

array
[1 2 3]
array
[3 2 3]


In [21]:
import pandas as pd

In [22]:
%matplotlib inline

Matplotlib is building the font cache; this may take a moment.
